# Generated by Django 2.1.7 on 2019-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=3)),
                ('os', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android')], default='ios', max_length=10)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('installs', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
